version: '3.5'

services:
  app:
    build: .docker/php
    working_dir: /app
    volumes:
      - .:/app
    environment:
      COMPOSER_HOME: /app/var/cache/composer
    # entrypoint: 'tail -f /dev/null'
